### ISSUE TITLE
what is this?

### ISSUE THREAD

**Issue by Boryyy** [RodrigoCabaco/InstaDel#1]
![image](https://user-images.githubusercontent.com/60760570/114104785-d5f02400-98cb-11eb-960a-db7c41b5f5f7.png)

**Comment by RodrigoCabaco** [comment]
Hello, for some reason, on windows it displays that STOP! Which is  just the js console output...
On linux that does not happen.
But do not worry, as long as you see a message with 'request sent with username' .... you're fine.

**Comment by Boryyy** [comment]
okay thanks , i tried both linux shell and windows works perfect , nice work!

**Comment by RodrigoCabaco** [comment]
Quick note: if you comment line 48 you can see the actual browser and check wether or not the bot is actually sending the requests. 
Hope that helps!

**Comment by Boryyy** [comment]
yea i tried that and when i do it it doesnt show the STOP , hmm , anyway thanks for ur time!

**Comment by RodrigoCabaco** [comment]
This Issue has Been fixed in the latest update

**Comment by Boryyy** [comment]
thanks <3
